export const DELETE_INGREDIENT:'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const ADD_INGREDIENT:'ADD_INGREDIENT' = 'ADD_INGREDIENT';

export const GET_ITEMS_REQUEST:'GET_ITEMS_REQUEST' = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS:'GET_ITEMS_SUCCESS' = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED:'GET_ITEMS_FAILED' = 'GET_ITEMS_FAILED';

export const GET_ORDERS_REQUEST:'GET_ORDERS_REQUEST' = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS:'GET_ORDERS_SUCCESS' = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILED:'GET_ORDERS_FAILED' = 'GET_ORDERS_FAILED';
export const ADD_BUN:'ADD_BUN' = 'ADD_BUN';

export const OPEN_MODAL:'OPEN_MODAL' = 'OPEN_MODAL';
export const CLOSE_MODAL:'CLOSE_MODAL' = 'CLOSE_MODAL';

export const UPDATE_ITEM:'UPDATE_ITEM' = 'UPDATE_ITEM';
export const REMOVE_BUN:'REMOVE_BUN' = 'REMOVE_BUN';

export const CLEAR_INGREDIENTS:'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS';
export const CLEAR_ORDER_NUMBER :'CLEAR_ORDER_NUMBER' = 'CLEAR_ORDER_NUMBER';

export const GET_PASS_REQUEST:'GET_PASS_REQUEST' = 'GET_PASS_REQUEST';
export const GET_PASS_SUCCESS:'GET_PASS_SUCCESS' = 'GET_PASS_SUCCESS';
export const GET_PASS_FAILED:'GET_PASS_FAILED' = 'GET_PASS_FAILED';
export const GET_REG_NEW_USER_REQUEST:'GET_REG_NEW_USER_REQUEST' = 'GET_REG_NEW_USER_REQUEST';
export const GET_REG_NEW_USER_SUCCESS:'GET_REG_NEW_USER_SUCCESS' = 'GET_REG_NEW_USER_SUCCESS';
export const GET_REG_NEW_USER_FAILED:'GET_REG_NEW_USER_FAILED' = 'GET_REG_NEW_USER_FAILED';
export const GET_NEW_PASSWORD_REQUEST:'GET_NEW_PASSWORD_REQUEST' = 'GET_NEW_PASSWORD_REQUEST';
export const GET_NEW_PASSWORD_SUCCESS:'GET_NEW_PASSWORD_SUCCESS' = 'GET_NEW_PASSWORD_SUCCESS';
export const GET_NEW_PASSWORD_FAILED:'GET_NEW_PASSWORD_FAILED' = 'GET_NEW_PASSWORD_FAILED';
export const GET_LOGIN_USER_REQUEST:'GET_LOGIN_USER_REQUEST' = 'GET_LOGIN_USER_REQUEST';
export const GET_LOGIN_USER_SUCCESS: 'GET_LOGIN_USER_SUCCESS'= 'GET_LOGIN_USER_SUCCESS';
export const GET_LOGIN_USER_FAILED: 'GET_LOGIN_USER_FAILED' = 'GET_LOGIN_USER_FAILED';
export const GET_LOGOUT_USER_REQUEST:'GET_LOGOUT_USER_REQUEST' = 'GET_LOGOUT_USER_REQUEST';
export const GET_LOGOUT_USER_SUCCESS: 'GET_LOGOUT_USER_SUCCESS'= 'GET_LOGOUT_USER_SUCCESS';
export const GET_LOGOUT_USER_FAILED: 'GET_LOGOUT_USER_FAILED'= 'GET_LOGOUT_USER_FAILED';
export const GET_USER_DATA_REQUEST:'GET_USER_DATA_REQUEST' = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS' = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILED:'GET_USER_DATA_FAILED' = 'GET_USER_DATA_FAILED';
export const GET_UPDATE_USER_REQUEST: 'GET_UPDATE_USER_REQUEST'= 'GET_UPDATE_USER_REQUEST';
export const GET_UPDATE_USER_SUCCESS:'GET_UPDATE_USER_SUCCESS' = 'GET_UPDATE_USER_SUCCESS';
export const GET_UPDATE_USER_FAILED:'GET_UPDATE_USER_FAILED' = 'GET_UPDATE_USER_FAILED';
// export const GET_REFRESH_TOKEN_REQUEST:'GET_REFRESH_TOKEN_REQUEST' = 'GET_REFRESH_TOKEN_REQUEST';
// export const GET_REFRESH_TOKEN_SUCCESS: 'GET_REFRESH_TOKEN_SUCCESS' = 'GET_REFRESH_TOKEN_SUCCESS';
// export const GET_REFRESH_TOKEN_FAILED: 'GET_REFRESH_TOKEN_FAILED' = 'GET_REFRESH_TOKEN_FAILED';