export const ORDERS_FEED_USER_CONNECT = 'ORDERS_FEED_USER_CONNECT';
export const ORDERS_FEED_USER_DISCONNECT = 'ORDERS_FEED_USER_DISCONNECT';

export const ORDERS_FEED_USER_WS_CONNECTING = 'ORDERS_FEED_USER_WS_CONNECTING';
export const ORDERS_FEED_USER_WS_OPEN = 'ORDERS_FEED_USER_WS_OPEN';
export const ORDERS_FEED_USER_WS_CLOSE = 'ORDERS_FEED_USER_WS_CLOSE';
export const ORDERS_FEED_USER_WS_MESSAGE = 'ORDERS_FEED_USER_WS_MESSAGE';
export const ORDERS_FEED_USER_WS_ERROR = 'ORDERS_FEED_USER_WS_ERROR';



export const connectOrdersUser = (url) => ({
    type: ORDERS_FEED_USER_CONNECT,
    payload: url
});

export const disconnectOrdersUser = () => ({
    type: ORDERS_FEED_USER_DISCONNECT,
});

