export const ORDERS_FEED_ALL_CONNECT = 'ORDERS_FEED_ALL_CONNECT';
export const ORDERS_FEED_ALL_DISCONNECT = 'ORDERS_FEED_ALL_DISCONNECT';

export const ORDERS_FEED_ALL_WS_CONNECTING = 'ORDERS_FEED_ALL_WS_CONNECTING';
export const ORDERS_FEED_ALL_WS_OPEN = 'ORDERS_FEED_ALL_WS_OPEN';
export const ORDERS_FEED_ALL_WS_CLOSE = 'ORDERS_FEED_ALL_WS_CLOSE';
export const ORDERS_FEED_ALL_WS_MESSAGE = 'ORDERS_FEED_ALL_WS_MESSAGE';
export const ORDERS_FEED_ALL_WS_ERROR = 'ORDERS_FEED_ALL_WS_ERROR';

export const connectOrdersAll = (url) => ({
    type: ORDERS_FEED_ALL_CONNECT,
    payload: url
});

export const disconnectOrdersAll = () => ({
    type: ORDERS_FEED_ALL_DISCONNECT,
});


