import {ORDERS_FEED_USER_CONNECT,
    ORDERS_FEED_USER_DISCONNECT,
    ORDERS_FEED_USER_WS_CONNECTING,
    ORDERS_FEED_USER_WS_OPEN,
    ORDERS_FEED_USER_WS_CLOSE,
    ORDERS_FEED_USER_WS_MESSAGE,
    ORDERS_FEED_USER_WS_ERROR
} from "../actions/ordersFeedUserAction";

import {ORDERS_FEED_ALL_CONNECT,
    ORDERS_FEED_ALL_DISCONNECT,
    ORDERS_FEED_ALL_WS_CONNECTING,
    ORDERS_FEED_ALL_WS_OPEN,
    ORDERS_FEED_ALL_WS_CLOSE,
    ORDERS_FEED_ALL_WS_MESSAGE,
    ORDERS_FEED_ALL_WS_ERROR
} from "../actions/ordersFeedAllAction";

export type TWsActionTypes = {
    wsConnect: typeof ORDERS_FEED_USER_CONNECT | typeof ORDERS_FEED_ALL_CONNECT;
    wsDisconnect: typeof ORDERS_FEED_USER_DISCONNECT | typeof ORDERS_FEED_ALL_DISCONNECT;
    wsConnecting: typeof ORDERS_FEED_USER_WS_CONNECTING | typeof ORDERS_FEED_ALL_WS_CONNECTING;
    onOpen: typeof ORDERS_FEED_USER_WS_OPEN | typeof ORDERS_FEED_ALL_WS_OPEN;
    onClose: typeof ORDERS_FEED_USER_WS_CLOSE | typeof ORDERS_FEED_ALL_WS_CLOSE;
    onError: typeof ORDERS_FEED_USER_WS_ERROR | typeof ORDERS_FEED_ALL_WS_ERROR;
    onMessage: typeof ORDERS_FEED_USER_WS_MESSAGE | typeof ORDERS_FEED_ALL_WS_MESSAGE;
};